# Generated by Django 5.2.1 on 2025-05-24 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('address', models.TextField()),
                ('referral_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_data', to='app.whatsappcontact')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
