# Generated by Django 5.2.1 on 2025-05-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_clientdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdata',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
